### PR TITLE
Remove Barryvdh\Debugbar\ServiceProvider

### PR DESCRIPTION
**Pull request by ahmed-aliraqi**
Already registered by package discover in 5.5

### CODE REVIEW

**Comment by ahmed-aliraqi** [comment]
Finished with me @khaled-dev @AlShahawi 😎😎

**Comment by AlShahawi** [comment]
Thanks, @ahmed-aliraqi  .

**Comment by ahmed-aliraqi** [comment]
Will you make friendship with me وﻻ ايه  @AlShahawi ??

**Comment by ahmed-aliraqi** [comment]
BolBol yabo El-balabel
All people are his disciples 😎😎
@khaled-dev

**Pull request merged**
